### ISSUE TITLE
Vars styles!

### ISSUE THREAD

**Issue by testacode** [taskworld/atom-lcov#5]
Sorry to raise an issue but I wanted to know your color theme configuration for the 'rainbowish' colored value please if you are so kind.

![image](https://user-images.githubusercontent.com/1852080/30517585-0a538580-9b3b-11e7-9a46-391742569f56.png)

Thanks!

**Comment by dtinth** [comment]
Thanks for asking, here you go:

https://medium.com/hacking-atom/rainbow-strings-94a2b99cf8b7
